### ISSUE TITLE
Installation not working on Ubuntu Trusty (Mythbuntu)

### ISSUE THREAD

**Issue by radredgreen** [MythTV-Clients/MythExpress#3]
Hi George,

I'm trying to install and investigate this package after a long overdue upgrade to mythtv 0.28 and I've been stuck on installation for a few hours.  

I'm a novice with node.  When I follow the install directions verbatim from the readme, I get the following error after running`npm install`, looking for errors in npm-debug.log

919 error Error: No compatible version found: xmlbuilder@'^4.1.0'

I've gotten further with later versions of node but keep getting errors.  For example, with v0.10.20, I get past npm install and when I run `node mythexpress.js` I get:

`[Tue Apr 19 2016 21:21:57 GMT-0500 (CDT)] INFO Mythbackend on mythbackend1: 192.168.10.19
Content API version : undefined

/root/MythExpress/mythtv.js:1193
                                        finished(null);
                                        ^
TypeError: object is not a function
    at /root/MythExpress/mythtv.js:1193:41
    at /root/MythExpress/mythtv.js:197:13
    at IncomingMessage.<anonymous> (/root/MythExpress/mythtv.js:168:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
`
Would you mind updating the readme with new installation instructions.

Thanks,
Red

**Comment by gnassas** [comment]
Hi Red, sorry about the problems. I updated the readme to install node v4 and removed the part needed about patches which have been long committed. I was able to install and build a clean checkout on debian so it should work for you. The whole project needs attention that I don't have time to give just now. When I wrote it node was too new to be packaged but now it's in stable distros so I have to switch to depend on those. One of these days…

Let me know if you get things working so I can close this issue.
- George

**Comment by radredgreen** [comment]
I tried following the new instructions but still get an error in mdns.  See below.

$ node mythexpress.js 
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
express deprecated app.configure: Check app.get('env') in an if statement mythexpress.js:38:5
connect deprecated methodOverride: use method-override npm module instead mythexpress.js:43:21
express deprecated app.configure: Check app.get('env') in an if statement mythexpress.js:47:5
express deprecated app.configure: Check app.get('env') in an if statement mythexpress.js:53:5
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot about.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot frontends.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot index.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot manifest.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot recordings.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot streams.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot templates.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot ui.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot videos.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO     Boot watch.js
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO create a socket server on:
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO { address: '::', family: 'IPv6', port: 6565 }
[Wed Apr 20 2016 13:10:22 GMT-0500 (CDT)] INFO MythTV Express server listening on port 6565 in development mode
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/root/MythExpress/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/root/MythExpress/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/root/MythExpress/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
$

**Comment by gnassas** [comment]
None of this touches my code, its happening before anything of mine gets called. It looks like the mdns module is choking on myth's IPv6 address but I don't immediately see why.

This might take a while so as a workaround you could edit the file:

```
node_modules/mdns/lib/resolver_sequence_tasks.js
```

around line 150 where it says:

```
var families = options.families || [4, 6];
```

and change it to:

```
var families = options.families || [4];
```

That got things working on my Debian system. I was initially testing on Mac where none of this happens. I guess there's something specific in the Linux getaddrinfo.

**Comment by radredgreen** [comment]
Thanks, Everything works now.

To sum up for anyone trying to follow in my foot steps.  I needed to do the following for this to work on Mythbuntu 14.04 with Mythtv 2:0.28.0+fixes.20160418.b4e03c8-0ubuntu0mythbuntu4 release:

sudo apt-get install curl git-core g++ libavahi-compat-libdnssd-dev build-essential libssl-dev

git clone git://github.com/creationix/nvm.git ~/.nvm
. ~/.nvm/nvm.sh
nvm install v4

git clone https://github.com/MythTV-Clients/MythExpress
cd MythExpress
npm install

edit node_modules/mdns/lib/resolver_sequence_tasks.js line 146 to end with [4];
edit mythtv/mythprotocol.js line 56 to add "88" : "XmasGift", and change the Latest to 88.

node mythexpress.js

Then everything worked nicely for me. 

George, It may be nice to post some screenshots for those browsing through to get a taste of app.

The responsiveness is quite good on iPad and iPhone.  Here are a few wishes off the top of my head which have nothing to do with the app.  I wish there wasn't a need to wait for the transcoding to finish before moving forward and back in the show.  I also wish there was a way to create the stream with commercials removed.  Finally I would like to be able to stream video iso's.  Perhaps I just need to do a little more research to learn how to set these all up.  

Nice work with the app.
